add solution fpr Lecture 6
Letto228/Angular-learnjs-211223 pull request #71
Opened 2024-01-25 11:34 UTC by Arthur-Ming

2024-01-27 04:59 UTC, Letto228 requested changes
Привет!
Отличный МР, классный код👍
Есть пару вопросов/рекомендаций, посмотри, пожалуйста.

Но есть и один недочет: а что если изменится входной массив? Не увидел, чтобы где-то обрабатывался данный кейс🤔

2024-01-27 04:59 UTC, Letto228 commented on src/app/pages/products-list/pagination-control/pagination-control.component.ts
> +        return this.activeIndex === index;
Похожие конструкции, в которых по какому-то значению определяется какие данные возвращать, отлично укладывается в тернарный оператор:
```suggestion
        return this.activeIndex === null ? false : this.activeIndex === index;
```

А можно пойти еще дальше и воспользоваться вычислением значения через логический оператор `&&`:
```suggestion
        return this.activeIndex !== null && this.activeIndex === index;
```
OR
```suggestion
        const isActiveIndexDefined = this.activeIndex !== null;
        
        return isActiveIndexDefined && this.activeIndex === index;
```

2024-01-27 04:59 UTC, Letto228 commented on src/app/shared/pagination/utils.ts
> +export function createPageIndexes(arrowLength: number, chankSize: number): number[] {
Мы с командой пришли к выводу, что скидывать все утили в один файл - плохая практика, т.к. этот файл, в процессе, очень быстро превращается в помойку. Намного лучше смотрится, если для каждой. экспортируемой утили создать собственный файл внутри `utils` директории: `utils/create-page-indexes.ts` and `utils/slice-group.ts`

2024-01-27 04:59 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +        if (this.pageIndexes) {
Проверка, конечно, это хорошо, но нужна ли она тут? Можно ли вызвать `next`/`end`/`selectIndex`, если отсутствует `pageIndexes`?

2024-01-27 04:59 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +        if (!this.appPaginationOf || !this.appPaginationOf.length) {
На мой взгляд, можно было бы сделать чуть проще и не менее прозрачнее
```suggestion
        if (!this.appPaginationOf?.length) {
```

2024-01-29 07:36 UTC, Arthur-Ming commented on src/app/pages/products-list/pagination-control/pagination-control.component.ts
> +        return this.activeIndex === index;
Ок

2024-01-29 07:36 UTC, Arthur-Ming commented on src/app/shared/pagination/utils.ts
> +export function createPageIndexes(arrowLength: number, chankSize: number): number[] {
Ok

2024-01-29 07:48 UTC, Arthur-Ming commented on src/app/shared/pagination/pagination.directive.ts
> +        if (this.pageIndexes) {
Проверка в next() и back() нужна была, т.к. кнопки next и back рендерятся даже если this.pageIndexes === null, что, наверное, не лучшее решение.
Это исправил, теперь проверка не нужна

2024-01-29 07:50 UTC, Arthur-Ming commented on src/app/shared/pagination/pagination.directive.ts
> +        if (!this.appPaginationOf || !this.appPaginationOf.length) {
Согласен,  сделал немного по другому

2024-01-29 13:34 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +    ngOnChanges({appPaginationOf}: SimpleChanges): void {
А нам не стоит ли реагировать на изменение `appPaginationChankSize`?

2024-01-29 13:34 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +    private updatePageIndexes(): void {
А зачем нам данный метод?

2024-01-29 13:34 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +        this.setPageIndexes();
А нужно ли вызывать данный метод в `OnInit`?

2024-02-02 17:11 UTC, Arthur-Ming commented on src/app/shared/pagination/pagination.directive.ts
> +    ngOnChanges({appPaginationOf}: SimpleChanges): void {
да, стоит

2024-02-02 17:11 UTC, Arthur-Ming commented on src/app/shared/pagination/pagination.directive.ts
> +    private updatePageIndexes(): void {
ничего нового не делает, не нужен

2024-02-02 17:13 UTC, Arthur-Ming commented on src/app/shared/pagination/pagination.directive.ts
> +        this.setPageIndexes();
получается вызывается два раза -- в ngOnInit и ngOnChanges,  
достаточно вызывать только в  ngOnChanges

2024-02-05 15:15 UTC, Letto228 approved these changes
Все круто - аппрув!

2024-02-05 15:15 UTC, closed without merging