feat: add category navigation
Letto228/Angular-learnjs-211223 pull request #90
Opened 2024-02-08 02:43 UTC by Shutov447

вроде работает, но я почти ничего не написал. Так и должно быть?

2024-02-08 11:25 UTC, Letto228 requested changes
Привет!
В целом, да, ДЗ маленькое и простое)
Но у нас сейчас есть недочет, который считается даже багом, давай доработаем. Если захочется еще усложнить задание - можно оптимизировать конфиг навигации: убрать 2 конфига подключающих `ProductsListComponent` через `path` и создать для них 1 конфиг работающий через `matcher`, должно быть интересно 🙃

2024-02-08 11:25 UTC, Letto228 commented on src/app/pages/products-list/products-list.component.ts
> +        this.activatedRoute.paramMap.subscribe(paramMap => {
Смотри, у нас сейчас есть такая проблема: нет отписки от потока, из-за чего возникнет утечка памяти) согласись, звучит так себе.

Давай сделаем один из 2х вариантов:
1. Реализовать отписку от потока
2. Реализовать все без явной подписки (т.е. уместить логику в `products$` потоке)

Мне больше нравится второй вариант, он добавляет меньше логики и кода, проще говоря, более лаконичный)

2024-02-08 17:29 UTC, Shutov447 commented on src/app/pages/products-list/products-list.component.ts
> +        this.activatedRoute.paramMap.subscribe(paramMap => {
усложнять не хочется). Подписку я отменил методом, который уже знаю

2024-02-12 09:05 UTC, Letto228 approved these changes
Отлично - аппрув!

2024-02-12 09:06 UTC, closed without merging